import "./globals.css";
import Header from "./(Header)/Header"
import Footer from "./(Footer)/Footer";
export const metadata = {
  title: "Cocktail",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="pb-[150px] pt-[65vh] duration-300 max-w-[1320px] px-custom max-md:pl-custom max-[1400px]:max-w-[1140px] max-[1200px]:max-w-[960px]  max-lg:max-w-[720px] max-md:max-w-[450px] mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
